spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fxdeals
    username: postgres
    password: younes
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
